admissionWhitelistPatterns:
- namePattern: REGION-docker.pkg.dev/PROJECT_ID/REGISTRY_NAME/bank-of-anthos/*
- namePattern: REGION-docker.pkg.dev/PROJECT_ID/REGISTRY_NAME/boutique/*
- namePattern: REGION-docker.pkg.dev/PROJECT_ID/REGISTRY_NAME/*
- namePattern: gcr.io/gke-release/asm/canonical-service-controller:*
- namePattern: k8s.gcr.io/metrics-server/metrics-server:*
- namePattern: gcr.io/kubebuilder/kube-rbac-proxy:*
- namePattern: k8s.gcr.io/serve_hostname:*
- namePattern: gcr.io/config-management-release/hydration-controller:*
- namePattern: k8s.gcr.io/pause:*
defaultAdmissionRule:
  enforcementMode: ENFORCED_BLOCK_AND_AUDIT_LOG
  evaluationMode: ALWAYS_DENY
globalPolicyEvaluationMode: ENABLE
name: projects/PROJECT_ID/policy
