apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  policyController:
    enabled: true
  git:
    syncRepo: https://github.com/mathieu-benoit/my-kubernetes-deployments
    syncBranch: main
    secretType: none
    policyDir: .
  patches:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: git-importer
      namespace: config-management-system
    spec:
      template:
        spec:
          containers:
          - name: importer
            resources:
              limits:
                memory: "500Mi"