applySpecVersion: 1
spec:
  policyController:
    enabled: true
    templateLibraryInstalled: false
    referentialRulesEnabled: false
    logDeniesEnabled: false
  configSync:
    enabled: true
    sourceFormat: hierarchy
    syncRepo: https://github.com/mathieu-benoit/my-kubernetes-deployments
    syncBranch: main
    secretType: none
    policyDir: .
